#!/bin/bash
# "##########################################"
# "##########################################"
# "#                                                                                                              #"
# "# Screen Recording v 0.44 beta                                                         #"
# "# daniel glenn                                                                                       #"
# "#                                                                                                              #"
# "# 09.Feb.2013	                                                                            #"
# "#                                                                                                              #"
# "##########################################"
# "##########################################"

# MIT license - http://www.opensource.org/licenses/mit-license.php

################################################
# Configuration
################################################

# Set output folder
OutDir=$(echo ~/Videos/)
echo $OutDir
#Random Video Name
curDate=$(date +%Y_%h_%d_%H%M%S)

#Video rec Name
rec="tmp_rec_"$curDate".mkv"

#Video final Name
recF="tmp_final_"$curDate".mkv"

# FPS
r="-r 30"

#Audio codec
acodec="-acodec pcm_s16le"

#Audio input - ist bei mir der Alsa device vom USB Micro von meinem Kopfhoerer
i="-i hw:2,0"

#Video codec and compress mode
vcodec="-vcodec libx264 -preset ultrafast -crf 0"

# rec thread count, wenn 0 dann alle moeglichen
# t="-threads 0"

################################################
# Configuration Video Meta-Data
################################################

## title
title="insert your title"

## author
author="inerst your name"

## comment
comment="insert your comment"

## year
year=$(date +%Y)

## copyright
copyright="$year©insert information"

################################################
# Check Input Parameter
################################################

if [ "$1" == "-h" -o "$1" == "--help"  ]; then
        echo -e "\nUsage: recording [OPTION]"
        echo "Option    :"
        echo "  720     :   set hd720 Screen size"
        echo "  1080    :   set hd1080 Screen size for full HD"
        exit 0
fi

if [ $# -eq 0 ]; then
        echo -e "\nUsage: recording [OPTION]"
        echo "'recording --help' for more information."
        exit 32
fi

# set var fuer Screen size
s=""

if [ $# -eq 1 ]; then
    if [ $1 == "720" ]; then
        s="-s hd720"
    fi
    if [ $1 == "1080" ]; then
        s="-s hd1080"
    fi
    
    if [ $1 != "720" ] && [ $1 != "1080" ]; then
        echo -e "\nUsage: recording [OPTION]"
        echo "'recording --help' for more information."
        exit 32
    fi
fi

################################################
# Check output-folder 
################################################

if [ -d $OutDir ]; then
	cd $OutDir
else 
	mkdir $OutDir
	cd $OutDir
fi 

################################################
# Run Recording 
################################################

ffmpeg -f alsa -ac 1  $i -f x11grab $r $s -i :0.0 $acodec $vcodec $rec

#echo "schreibe Meta-Data in das Video"
ffmpeg -i $rec -vcodec copy -acodec copy -metadata title="$title" -metadata comment="$comment" -metadata author="$author" -metadata year="$year" -metadata copyright="$copyright" -metadata Date="$(date)" $recF

# loeschen vom video tmp file
rm -f $rec

# Alles war o.k und jetzt beenden
exit 0
